[workspace]
resolver = "2"
members = [
  "engine",
  "crates/*",
]
package.version = "0.3.0"
package.rust-version = "1.96.0"
package.edition = "2024"
package.publish = false

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
strip = true

[workspace.dependencies]
image = "0.25.10"
tracing = "0.1.44"
thiserror = "2.0.18"
gltf = "1.4.1"
