name: MD Render automatic build and release

# Release when a tag like v0.1.0 is pushed
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  # Asset artifact preparation
  prepare-example-assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
      
      - name: Upload example assets
        uses: actions/upload-artifact@v4
        with:
          name: example-assets
          path: engine/examples/assets/

  # Linux - Build application and upload artifact
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build basic example
        run: cargo build --examples --release --target x86_64-unknown-linux-gnu

      - name: Upload example binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: example-binaries-x86_64-unknown-linux-gnu
          path: | 
            target/x86_64-unknown-linux-gnu/release/examples/basic
            target/x86_64-unknown-linux-gnu/release/examples/high_poly

  # Windows - Build application and upload artifact
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build basic example
        run: cargo build --examples --release --target x86_64-pc-windows-msvc
      
      - name: Upload basic example artifact
        uses: actions/upload-artifact@v4
        with:
          name: example-binaries-x86_64-pc-windows-msvc
          path: |
            target/x86_64-pc-windows-msvc/release/examples/basic.exe
            target/x86_64-pc-windows-msvc/release/examples/high_poly.exe

  # Download artifact and create release
  release:
    needs: [build-linux, build-windows]
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          draft: true 
          prerelease: false
          release_name: ${{ github.ref }}
          tag_name: release-${{ github.ref }}
          body_path: CHANGELOG.md

      # Linux release assembly
      - name: Download examples artifact (Linux)
        uses: actions/download-artifact@v4
        with:
          name: example-binaries-x86_64-unknown-linux-gnu
          path: MDR-linux

      - name: Download assets artifact (Linux)
        uses: actions/download-artifact@v4
        with:
          name: example-assets
          path: MDR-linux/assets
      
      # Windows release assembly
      - name: Download examples artifact (Windows)
        uses: actions/download-artifact@v4
        with:
          name: example-binaries-x86_64-pc-windows-msvc
          path: MDR-windows

      - name: Download assets artifact (Windows)
        uses: actions/download-artifact@v4
        with:
          name: example-assets
          path: MDR-windows/assets

      # Zip Linux and Windows artifacts
      - name: Zip artifacts
        run: |
          sudo apt-get install -y zip
          cd MDR-linux
          zip -r ../linux-build-results.zip *
          cd ../MDR-windows
          zip -r ../windows-build-results.zip *
          cd ..

      # Upload release zips
      - name: Upload release artifact (Linux)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: linux-build-results.zip 
          asset_name: MDR-examples-x64-Linux.zip
          asset_content_type: application/zip

      - name: Upload release artifact (Windows)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: windows-build-results.zip 
          asset_name: MDR-examples-x64-Windows.zip
          asset_content_type: application/zip
